### ISSUE TITLE
Can you provide a runnable version of train.py using one of the public dataset 

### ISSUE THREAD

**Issue by fucusy** [lpworld/PURS#2]
I met the filename doesn't error while running the `train.py`

```(purs) ➜  PURS git:(master) python train.py
/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
Traceback (most recent call last):
  File "train.py", line 95, in <module>
    data = pd.read_csv('test.txt', names=['utdid','vdo_id','click','hour'])
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File test.txt does not exist
```

**Comment by lpworld** [comment]
Hi Qiang,

Thanks for your interest in the repository. You need to provide your own choice of datasets in the "test.txt" file. This is the file containing the user-item records, and you need to create it yourself. It is in the format of ("userid","itemid","rating","time"). To help you better understand, I have uploaded a sample version of the "test.txt" file. Please feel free to use it.

Best Regards,
Pan

**Comment by fucusy** [comment]
Hi, Pan, 
Thanks for your quick response!  The sample "test.txt" is great, it helps me understand the program!
